version: "3"

services:
  app:
    build: .
    volumes:
      - ./src:/app
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: snippetbox
      MYSQL_PASSWORD: snippetbox
      MYSQL_ROOT_PASSWORD: snippetbox
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default
